export const members = [
  //Executive Committee
  { name: "Mr. Mukesh Sahu", position: "Branch Counselor", branch: "", image: "/mukesh sahu.jpg", description: "Mukesh Sahu, IEEE GTBIT SB Branch Counselor, is adedicated advisor who provides guidance on bothtechnical and professional levels", socials: { instagram: "https://www.instagram.com/mukeshsahugtbit/", linkedin: "https://linkedin.com/in/mukesh-sahu-b087466", twitter: "#", }, },
  {name: "Sahib Preet Singh",position: "Mentor",branch: "",image:"/Sahib Preet Singh.png",description:"Sahib Preet Singh, Mentor of the IEEE GTBIT Student Branch, guides the branch's technical endeavors and cultivates a strong sense of community among its members.",socials: {instagram: "https://www.instagram.com/sahiibbb/?hl=en",linkedin: "https://www.linkedin.com/in/sahib-preet-singh/",twitter: "#",},},
  { name: "Falkeet Singh", position: "Chairperson", branch: "CSE 2nd Year)", image: "falkeet.jpg", description: "Leads the organization and oversees all operations.", socials: { instagram: "https://www.instagram.com/falkeet_singh1/?hl=en", linkedin: "https://www.linkedin.com/in/falkeet-singh/", twitter: "#", }, },
  { name: "Angaddeep Singh", position: "Vice Chairperson", branch: "CSE (2nd Year)", image: "Angaddeep Singh.jpeg", description: "Assists the chairperson and manages responsibilities in their absence.", socials: { instagram: "https://www.instagram.com/angad3104/?hl=en", linkedin: "https://www.linkedin.com/in/angaddeepsingh05/", twitter: "#", }, },
  { name: "Japjot Singh", position: "Student Advisor and Treasurer", branch: "CSE (3rd Year)", image: "japjot singh.jpg", description: "Manages finances and provides strategic guidance.", socials: { instagram: "https://www.instagram.com/japjot.singhh/?hl=en", linkedin: "https://www.linkedin.com/in/japjot-singh-14216b290/", twitter: "#", }, },
  { name: "Kulreet Kaur", position: "General Secretary", branch: "CSE (3rd Year)", image: "Reet kaur Ahuja.jpg", description: "Coordinates between teams to ensure smooth functioning and oversees team meetings.", socials: { instagram: "https://www.instagram.com/reettt.kaur?igsh=MTJpYjIzMDQwbmpneg", linkedin: "https://www.linkedin.com/in/kulreet-kaur-74470a18a/?originalSubdomain=in", twitter: "#", }, },
  { name: "Vidit Dalmia", position: "Joint Secretary", branch: "AI-DS (3rd Year)", image: "Vidit Dalmia.png", description: "Supports the General Secretary and assists in administrative tasks", socials: { instagram: "https://www.instagram.com/vi._.it/?hl=en", linkedin: "https://www.linkedin.com/in/vidit-dalmia", twitter: "#", }, },
  { name: "Vinay Dhaka", position: "Joint Secretary", branch: "ECE ( 3rd Year )", image: "/ Vinay Dhaka.jpg", description: "Supports the General Secretary and assists in administrative tasks", socials: { instagram: "", linkedin: "https://www.linkedin.com/in/vinay-dhaka-04239230a?trk=universal-search-cluster", twitter: "#", }, },
  

  //Human Resources
  { name: "Ashmeet Kaur", position: "Human Resources Lead", branch: "CSE-ML ( 2nd Year)", image: "Ashmeet Kaur.jpg", description: "Oversees internal affairs, team coordination and member management.", socials: { instagram: "https://www.instagram.com/kaurr_ash?igsh=b29jN3l2cHY5OXk=", linkedin: "https://www.linkedin.com/in/ashmeet-kaur-3301a82b8", twitter: "#", }, },
  { name: "Pragya Mehta", position: "Human Resources Coordinator", branch: "IT ( 1st Year )", image: "Pragya Mehta.jpg", description: "Assists in HR activities and maintains internal communication.", socials: { instagram: "https://www.instagram.com/_m.pragyaa?igsh=eTI2aXEwamtqOHB4", linkedin: "https://www.linkedin.com/in/pragya-mehta-a8253a324?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app", twitter: "#", }, },
  { name: "Nikita Khatter", position: "Human Resources Coordinator", branch: "IT ( 1st Year )", image: "Nikita Khatter.jpg", description: " Assists in HR activities and maintains internal communication.", socials: { instagram: "https://www.instagram.com/nikitakhatter_?igsh=MWZxNmliOTNmZzRuYQ==", linkedin: "https://www.linkedin.com/feed/?trk=guest_homepage-basic_google-one-tap-submit", twitter: "#", }, },
  
  //Electronics Team
  { name: "Piyush Thakur", position: "Electronics Team Head", branch: "ECE ( 3rd Year )", image: "Piyush.jpg", description: "Leads the electronics division and manages related projects.", socials: { instagram: "", linkedin: "https://www.linkedin.com/in/piyush-1013b7315?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app", twitter: "#", }, },
  { name: "Gautam Kumar", position: "Electronics Team Coordinator", branch: "ECE ( 2nd Year )", image: "Gautam Kumar.jpg", description: "Help in managing and executing electronics-related activities", socials: { instagram: "", linkedin: "https://www.linkedin.com/in/gautam-kumar-871156293?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app", twitter: "#", }, },
  { name: "Gurjyot Kaur", position: "Electronics Team Coordinator", branch: "ECE ( 2nd Year )", image: "/Gurjyot Kaur.jpg", description: "Help in managing and executing electronics-related activities", socials: { instagram: "https://www.instagram.com/gurjyot_22?igsh=MWp3dngxeWg0dzg5eA==", linkedin: "https://www.linkedin.com/in/gurjyot-kaur-759841318?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app", twitter: "#", }, },
  { name: "Brian Walter", position: "Electronics Team Coordinator", branch: "ECE ( 1st Year )", image: "Brian Walter.jpg", description: "Help in managing and executing electronics-related activities", socials: { instagram: "https://www.instagram.com/brian_walter10/profilecard/?igsh=cW5rdHNtMHV1YW85", linkedin: "https://www.linkedin.com/in/brian-walter-107bb4334?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app", twitter: "#", }, },
  { name: "Vihaan Gupta", position: "Electronics Team Coordinator", branch: "ECE ( 1st Year )", image: "/Vihaan Gupta.jpg", description: "Help in managing and executing electronics-related activities", socials: { instagram: "https://www.instagram.com/vihaan.gupta.15?igsh=MTl5dm96bGU3eThtdA==", linkedin: "https://www.linkedin.com/in/vihaan-gupta-15b4a5305?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app", twitter: "#", }, },
  
  //Technical Activities Committee
  { name: "Paras Nagshetty", position: "Technical Activities Committee Head", branch: "AI-DS ( 3rd Year )", image: "Paras.JPG", description: " Oversees all technical teams and ensures project execution.", socials: { instagram: "https://www.instagram.com/paras_pic?igsh=MWFuMmcyejJxbXA4Mw==", linkedin: "https://in.linkedin.com/in/paras-nagshetty-845b74275", twitter: "#", }, },
  { name: "Harmanjot Singh Nanda", position: "Technical Activities Committee Head", branch: "CSE ( 2nd Year )", image: "/harman nanda.jpeg", description: " Oversees all technical teams and ensures project execution.", socials: { instagram: "https://www.instagram.com/harmannanda_/", linkedin: "https://in.linkedin.com/in/harmanjot-singh-nanda-80794a292", twitter: "#", }, },
  
  //DSA Team
  { name: "Suhani Kaur Saluja", position: "DSA Team Lead", branch: "CSE-DS ( 1st Year )", image: "Suhani Kaur saluja.jpeg", description: "Leads the Data Structures and Algorithms (DSA) team and responsible for DSA training.", socials: { instagram: "https://www.instagram.com/salujasuhani_?igsh=eDgwZ3c5YXhlaWR2&utm_source=qr", linkedin: "https://www.linkedin.com/in/kaursalujasuhani?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app", twitter: "#", }, },
  { name: "Siddak Raj Singh", position: "DSA Team Coordinator", branch: "CSE ( 1st Year )", image: "SIDDAK RAJ SINGH.jpg", description: "Assist in DSA-related activities and mentorship.", socials: { instagram: "https://www.instagram.com/_siddak_18_?igsh=dHRnczQ2cDIxNGJk", linkedin: "https://www.linkedin.com/in/siddak-raj-singh-0a9484335?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app", twitter: "#", }, },
  { name: "Pushkar", position: "DSA Team Coordinator", branch: "IT ( 1st Year )", image: "/Pushkar Gupta.jpg", description: "Assist in DSA-related activities and mentorship.", socials: { instagram: "https://www.instagram.com/pushkar_gupta_17?igsh=a3JiMWxnODc5eWl5", linkedin: "https://www.linkedin.com/in/pushkar-gupta-3345b1329", twitter: "#", }, },
  
  //Web Development Team
  { name: "Vanshika Bansal", position: "Web Development Team Lead", branch: "CSE-DS ( 2nd Year )", image: "vanshika bansal.jpg", description: "Leads the Web Development team and responsible for Web Dev training.", socials: { instagram: "https://www.instagram.com/vanshikabansal_09/?hl=en", linkedin: "https://www.linkedin.com/in/vanshika-bansal-?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app", twitter: "#", }, },
  { name: "Eshmeet Kaur", position: "Web Development Team Co-Lead", branch: "CSE ( 1st Year )", image: "Eshmeet Kaur.jpg", description: "Assists in Web-Dev related activities and mentorship.", socials: { instagram: "https://www.instagram.com/eshkr_/profilecard/?igsh=MTJ4ODY4N3dkZjNzYg==", linkedin: "https://www.linkedin.com/in/eshmeet-kaur-542863329?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app", twitter: "#", }, },
  { name: "Sanvi Aswal", position: "Web Development Team Coordinator", branch: "ECE ( 1st Year )", image: "Sanvi.jpeg", description: "Assists in Web-Dev related activities and mentorship.", socials: { instagram: "https://www.instagram.com/_.sanvia_?igsh=MWpheXk2eG16MTJmag%3D%3D&utm_source=qr", linkedin: "https://www.linkedin.com/in/sanvi-aswal-a4a4ab313?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app", twitter: "#", }, },
  { name: "Gagandeep Kaur", position: "Web Development Team Coordinator", branch: "CSE ( 1st Year )", image: "Gagandeep.jpeg", description: "Assists in Web-Dev related activities and mentorship.", socials: { instagram: "", linkedin: "", twitter: "#", }, },
  
  //Creative Team
  { name: "Simar Kaur Renu", position: "Creative Head", branch: "CSE ( 2nd Year )", image: "Simar Kaur.jpeg", description: "Manages creative aspects, including design and content..", socials: { instagram: "https://www.instagram.com/simar.renu/profilecard/?igsh=MTF4cTNnZGNnaGtwZQ==", linkedin: "https://www.linkedin.com/in/simar-renu-28549b2b8?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app", twitter: "#", }, },
  
  //Editorial Team
  { name: "Sukhmeet Kaur", position: "Editorial Team Coordinator", branch: "CSE-DS ( 2nd Year )", image: "/Sukhmeet Kaur.jpg", description: "Assist in writing, editing, and proofreading content.", socials: { instagram: "https://www.instagram.com/thesukhmeetkaur/?hl=en", linkedin: "https://www.linkedin.com/in/sukhmeet-kaur-271421256/overlay/about-this-profile/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base%3BpNPKUaiSQbKm5K7cpAjKZQ%3D%3D", twitter: "#", }, },
  { name: "Avni Jain", position: "Editorial Team Coordinator", branch: "CSE-DS ( 1st Year )", image: "/Avni Jain.jpeg", description: "Assist in writing, editing, and proofreading content.", socials: { instagram: "https://www.instagram.com/avn_idk?igsh=OG82dGdwbjNibWQy&utm_source=qr", linkedin: "https://www.linkedin.com/in/avni-jain-56b375352?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app", twitter: "#", }, },
  { name: "Japleen Kaur", position: "Editorial Team Coordinator", branch: "CSE ( 1st Year ) ", image: "Japleen Kaur.jpeg", description: "Assist in writing, editing, and proofreading content.", socials: { instagram: "https://www.instagram.com/japleen__05?igsh=M3phOW1jczJtbzA=", linkedin: "https://www.linkedin.com/in/japleen-kaur-79667823b/", twitter: "#", }, },
  
  //Graphic Design Team
  { name: "Pranav chadha", position: "Graphic Design Team Coordinator", branch: "IT ( 2nd Year )", image: "PRANAV CHADHA.jpeg", description: "Assist in designing posters, banners, and creatives.", socials: { instagram: "https://www.instagram.com/heyy.pranavvvv?igsh=bGF4aHV4NGdkeHp3&utm_source=qr", linkedin: "http://linkedin.com/in/pranav-chadha-175911321", twitter: "#", }, },
  { name: "Hardit Singh Sindhu", position: "Graphic Design Team Coordinator", branch: "CSE ( 1st Year )", image: "Hardit Singh Sindhu.jpeg", description: "Assist in designing posters, banners, and creatives.", socials: { instagram: "https://www.instagram.com/har._.dit?igsh=MThwYWxmdGg3aHRmcw%3D%3D&utm_source=qr", linkedin: "https://www.linkedin.com/in/hardit-singh-sindhu-ba361633b?utm_source=share&utm_campaign=share_via&utm_content=", twitter: "#", }, },
  { name: "Teghbir Singh Chadha", position: "Graphic Design Team Coordinator", branch: "CSE ( 1st Year )", image: "TEGHBIR SINGH CHADHA.jpeg", description: "Assist in designing posters, banners, and creatives.", socials: { instagram: "https://www.instagram.com/teghbirsinghchadha", linkedin: "", twitter: "#", }, },
  { name: "Prathamjot Singh", position: "Graphic Design Team Coordinator", branch: "CSE ( 1st Year )", image: "Prathamjot Singh Bharaj.jpg", description: "Assist in designing posters, banners, and creatives.", socials: { instagram: "https://www.instagram.com/prathamj0t_1/", linkedin: "www.linkedin.com/in/prathamjot-singh-bharaj-249578294", twitter: "#", }, },
  { name: "Eknoor Singh", position: "Graphic Design Team Coordinator", branch: "CSE ( 1st Year )", image: "Eknoor Singh.jpeg", description: "Assist in designing posters, banners, and creatives.", socials: { instagram: "https://www.instagram.com/eknoorwtf/profilecard/?igsh=OWdsaHlmazNra3pw", linkedin: "https://www.linkedin.com/in/eknoor-singh-736718316?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app", twitter: "#", }, },
  
  //Outreach Team
  { name: "Vaibhav Singh", position: "Outreach Team Lead", branch: "ECE ( 1st Year )", image: "/Vaibhav Singh.jpg", description: "Manages external communications, collaborations, and promotions.", socials: { instagram: "https://www.instagram.com/vaibhav.singhh_?igsh=Nm5ybDlyYnN0Nzhy", linkedin: "", twitter: "#", }, },
  { name: "Maiesha Mehra", position: "Outreach Team Coordinator", branch: "AI-ML ( 1st Year )", image: "Maiesha Mehra.jpg", description: "Assist in handling partnerships and promotional activities.", socials: { instagram: "https://www.instagram.com/maieshamehra_?igsh=cTRkMWVoZHY2ajBs", linkedin: "https://www.linkedin.com/in/maiesha-mehra-a48669241", twitter: "#", }, },
  
  //Social Media Team
  { name: "Mansimar Kaur", position: "Social Media Lead", branch: "IT ( 2nd Year )", image: "Manss Kaur.jpg", description: " Manages social media strategy and engagement.", socials: { instagram: "https://www.instagram.com/mansimar.kaurrr?igsh=dHBpanNrbGFza3Bx", linkedin: "https://www.linkedin.com/in/mansimar-kaur-69504b310", twitter: "#", }, },
  { name: "Anhad Singh", position: "Social Media Co-Lead", branch: "CSE ( 2nd Year )", image: "Anhad Singh.jpeg", description: "Assist in content creation and posting on social media.", socials: { instagram: "https://www.instagram.com/anhad.102/profilecard/?igsh=amxxb2c1eG1lbTRv", linkedin: "https://www.linkedin.com/in/anhad-singh-136b171b8?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app", twitter: "#", }, },
  { name: "Saanvi Bhayana", position: "Social Media Coordinator", branch: "IT ( 1st Year )", image: "Saanvi bhayana.jpg", description: "Assist in content creation and posting on social media.", socials: { instagram: "https://www.instagram.com/saanvibhayana_?igsh=MWh3OHV1aWJ3dnVjMg==", linkedin: "", twitter: "#", }, },
  { name: "Sivkan Kaur", position: "Social Media Coordinator", branch: "AI-ML ( 1st Year )", image: "Sivkan Kaur.jpeg", description: "Assist in content creation and posting on social media.", socials: { instagram: "https://www.instagram.com/sivkannnn_?igsh=M2hwdXBmaDIwNjZ3&utm_source=qr", linkedin: "https://www.linkedin.com/in/sivkan-kaur-8928632a3?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app", twitter: "#", }, },
  
  //Photography Team
  { name: "Sanyam Nagpal", position: "Photography Team Lead", branch: "ECE ( 1st Year )", image: "Sanyam Nagpal.jpeg", description: "", socials: { instagram: "https://www.instagram.com/sanxyam_nagpal?igsh=YWd2anRtdDVnMXpl&utm_source=qr", linkedin: "https://www.linkedin.com/in/sanyam-nagpal-56b613300?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app", twitter: "#", }, },
  { name: "Abir Singh Gandhi", position: "Photography Team Coordinator", branch: "AI-ML ( 1st Year )", image: "Abir Singh Gandhi.jpg", description: "", socials: { instagram: "https://www.instagram.com/abirsinghgandhi/", linkedin: "www.linkedin.com/in/abir-singh-gandhi-7b2bab327", twitter: "#", }, },
  { name: "Rishi Raj Singh", position: "Photography Team Coordinator", branch: "ECE ( 1st Year )", image: "Rishiraj Singh.jpg", description: "", socials: { instagram: "", linkedin: "https://www.linkedin.com/in/rishi-raj-singh-218786353", twitter: "#", }, },
  
  //Webmaster
  { name: "Jas Singh Ajmani", position: "Webmaster", branch: "CSE ( 2nd Year )", image: "/Jas Singh Ajmani.jpg", description: "", socials: { instagram: "https://www.instagram.com/js.ajmani?igsh=MXNrbnVvcXUxbDI3dA==", linkedin: "https://www.linkedin.com/in/jas-singh-ajmani?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app", twitter: "#", }, },
  { name: "Manrai Singh", position: "Webmaster", branch: "CSE ( 1st Year )", image: "/Manrai Singh.jpg", description: "", socials: { instagram: "https://www.instagram.com/manrai_singh", linkedin: "https://www.linkedin.com/in/manrai-singh", twitter: "#", }, },
  
  //WIE 
  { name: "Navjyot Kaur", position: "WIE Chairperson", branch: "IT ( 2nd Year )", image: "Navjyot Kaur.jpeg", description: "Leads the Women in Engineering Affinity Group.", socials: { instagram: "https://www.instagram.com/navjyotkaurr/?hl=en", linkedin: "https://www.linkedin.com/in/navjyotkaur1510/", twitter: "#", }, },
  { name: "Gunisha Kukreja", position: "WIE Vice Chairperson", branch: "CSE ( 2nd Year )", image: "gunisha kaur.jpg", description: "Assists in managing WIE AG initiatives.", socials: { instagram: "https://www.instagram.com/gunisha___kaur?igsh=MTMxb2lqdm10N294Nw==", linkedin: "https://www.linkedin.com/in/gunisha-kaur-958837279?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app", twitter: "#", }, },
  { name: "Ishika Ahuja", position: "WIE General Secretary", branch: "CSE ( 2nd Year )", image: "Ishika Ahuja.jpg", description: "Oversees administration and communication within WIE AG.", socials: { instagram: "", linkedin: "https://www.linkedin.com/in/ishika-ahuja-62a0b6259?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app", twitter: "#", }, },
  { name: "Gurprajas Kaur Saluja", position: "WIE Coordinator", branch: "CSE-ML ( 1st Year )", image: "/ Gurprajas Kaur Saluja.jpg", description: " Supports WIE AG activities and handles any task at hand.", socials: { instagram: "https://www.instagram.com/gurprajas24?igsh=NDd3dGx1NWtjMDJp&utm_source=qr", linkedin: "https://www.linkedin.com/in/gurprajas-kaur-saluja-495208306?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app", twitter: "#", }, },
  { name: "Gurpratit Kaur Saluja", position: "WIE Coordinator", branch: "CSE-ML ( 1st Year )", image: "Gurpratit Kaur Saluja.jpeg", description: " Supports WIE AG activities and handles any task at hand.", socials: { instagram: "https://www.instagram.com/gpsaluja24?igsh=MXA1aGdwdDV5ZjI2Yw%3D%3D&utm_source=qr", linkedin: "https://www.linkedin.com/in/gurpratit-kaur-saluja-911926323?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app", twitter: "#", }, },
  { name: "Bavleen Kaur Saini", position: "WIE Coordinator", branch: "CSE ( 1st Year )", image: "Bavleen Kaur Saini.jpg", description: " Supports WIE AG activities and handles any task at hand.", socials: { instagram: "https://www.instagram.com/itssannieeee?igsh=anF4bHdreTRhOG9u", linkedin: "https://www.linkedin.com/in/bavleen-kaur-saini-482161339?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app", twitter: "#", }, },
  
  //Computer Society Chapter
  { name: "Supret RJ Kaur", position: "CS Chapter Chairperson", branch: "CSE ( 2nd Year )", image: "Supreet RJ Kaur.jpg", description: "Leads the Computer Society Chapter and its operations.", socials: { instagram: "https://www.instagram.com/qvrluvyt/?hl=en", linkedin: "https://www.linkedin.com/in/supret-rj-kaur-765658294/", twitter: "#", }, },
  { name: "Harjas Singh", position: "CS Chapter Vice Chairperson", branch: "CSE ( 2nd Year )", image: "Harjas Singh.jpg", description: "Assists the Chair in managing chapter activities.", socials: { instagram: "https://www.instagram.com/harjas_singh13?igsh=MTA1cDM2M2wwd3Jraw==", linkedin: "https://www.linkedin.com/in/harjas-singh-b9b060231?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app", twitter: "#", }, },
  { name: "Gagandeep Kaur", position: "CS Chapter General Secretary", branch: "CSE ( 2nd Year )", image: "Gagandeep Kaur.jpeg", description: "Handles administration and coordination in the chapter.", socials: { instagram: "https://www.instagram.com/dhanjal_gagandeep?igsh=ejZ4MjM3bnVjZ3dr&utm_source=qr", linkedin: "https://www.linkedin.com/in/gagandeep-kaur-5bba75298?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app", twitter: "#", }, },
  { name: "Japmanya Kaur", position: "CS Chapter Coordinator", branch: "CSE ( 1st Year )", image: "/ Japmanya Kaur.JPG", description: "Supports chapter activities and handling any task at hand.", socials: { instagram: "https://www.instagram.com/j_manyaz?igsh=NHVtMmR1anA3Z2h0&utm_source=qr", linkedin: "https://www.linkedin.com/in/japmanya?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app", twitter: "#", }, },
  { name: "Archita Garg", position: "CS Chapter Coordinator", branch: "CSE-DS ( 2nd Year )", image: "Archita Garg.webp", description: "Supports chapter activities and handling any task at hand.", socials: { instagram: "https://www.instagram.com/gunisha___kaur?igsh=MTMxb2lqdm10N294Nw==", linkedin: "https://www.linkedin.com/in/archita-garg-b8a5b831a?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app", twitter: "#", }, },
  { name: "Gurnoor singh", position: "CS Chapter Coordinator", branch: "CSE ( 1st Year )", image: "GURNOOR SINGH.png", description: "Supports chapter activities and handling any task at hand.", socials: { instagram: "", linkedin: "", twitter: "#", }, },

  //Research and Development Team
  { name: "Harshit", position: "Research and Development Lead", branch: "AI-DS ( 3rd Year )", image: "/ Harshit Khatri.jpg", description: "Leads research and development initiatives.", socials: { instagram: "", linkedin: "www.linkedin.com/in/harshit-khatri-352b15244?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app", twitter: "#", }, },
  { name: "Gurleen Kaur", position: "Research and Development Co-Lead", branch: "CSE-ML ( 2nd Year )", image: "gurleen kaur.jpeg", description: "Assist in R&D activities and supervision.", socials: { instagram: "", linkedin: "https://www.linkedin.com/in/gurleen-kaur-0b95352b1?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app", twitter: "#", }, },
  { name: "Ratti Noor Singh", position: "Research and Development Coordinator", branch: "CSE ( 1st Year )", image: "/ Rattinoor Singh.png", description: "Help in executing SIG activities.", socials: { instagram: "https://www.instagram.com/_sardarjjiii_?igsh=OXFsa3Fib3l1aXIw", linkedin: "https://www.linkedin.com/in/ratti-noor-singh-9646442b4?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app", twitter: "#", }, },
  { name: "Jismeet Singh", position: "Research and Development Coordinator", branch: " CSE-ML ( 1st Year )", image: "Jismeet Singh.jpg", description: "Help in executing SIG activities.", socials: { instagram: "https://www.instagram.com/jismeett?igsh=aWoxZ3BiZ3d5Mndp", linkedin: "https://www.linkedin.com/in/jismeet-singh-241191264?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app", twitter: "#", }, },

  //HackGTBIT
  { name: "Gurasees Singh", position: "HackGTBIT Lead", branch: "CSE ( 2nd Year )", image: "Gurasees Singh.jpg", description: " Leads hackathon-related initiatives and provides guidance.", socials: { instagram: "https://www.instagram.com/gurasees098?igsh=NDZmcHZyY2VyNHRk", linkedin: "", twitter: "#", }, },
  { name: "Lakshaya Bhardwaj", position: "HackGTBIT Co-Lead", branch: "CSE ( 1st Year )", image: "Lakshaya Bhardwaj.jpeg", description: "Assist in hackathon planning and execution.", socials: { instagram: "https://www.instagram.com/bhardwajlakshaya/", linkedin: "https://www.linkedin.com/in/lakshaya-bhardwaj-3367a0324/", twitter: "#", }, },
  { name: "Taranpreet Kaur", position: "HackGTBIT Coordinator", branch: "CSE ( 2nd Year )", image: "Taranpreet Kaur.jpg", description: "Support in organizing HackGTBIT events.", socials: { instagram: "https://www.instagram.com/_taranpreet_28?igsh=dWF0cHBkM21mNzls", linkedin: "https://www.linkedin.com/in/taranpreet-kaur-66a266335?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app", twitter: "#", }, },

  //Polaris
  { name: "Devanshi Singh", position: "Polaris Lead", branch: "IT ( 2nd Year )", image: "Devanshi Singh.jpeg", description: "Leads the POLARIS SIG and its initiatives.", socials: { instagram: "https://www.instagram.com/devanshiii.singh?igsh=MWl2MXZ6ZXM0dmFhMw%3D%3D&utm_source=qr", linkedin: "https://www.linkedin.com/in/devanshi-singh-737614284?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app", twitter: "#", }, },
  { name: "Jasleen Kaur", position: "Polaris Co-Lead", branch: "IT ( 2nd Year )", image: "Jasleen Kaur.jpg", description: " Assist in managing POLARIS SIG operations.", socials: { instagram: "https://www.instagram.com/jas._.leen07?igsh=MWpydTk1OTJ4aXAxYg==", linkedin: "https://www.linkedin.com/in/jasleen-kaur-b4123b319?trk=blended-typeahead", twitter: "#", }, },
  { name: "Jasnoor Kaur", position: "Polaris Coordinator", branch: "CSE ( 1st Year )", image: "/ Jasnoor Kaur.jpg", description: " Support in organizing POLARIS SIG events and tasks.", socials: { instagram: "https://www.instagram.com/jasnoorkaur_37?igsh=cGphMjcxNHNrcmts", linkedin: "https://www.linkedin.com/in/jasnoor-kaur-b19a58334?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app", twitter: "#", }, },

  //AI Masters
  { name: "Ashnoor Singh", position: "AI Masters Lead", branch: "CSE ( 2nd Year )", image: "Ashnoor Singh.jpg", description: "Leads the AI Masters Special Interest Group (AIM SIG) and responsible for AI & ML training.", socials: { instagram: "https://www.instagram.com/ashnoor71104?igsh=c25rYnEwdzFvbjdi", linkedin: "https://www.linkedin.com/in/ashnoor-singh-683640298?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app", twitter: "#", }, },
  { name: "Divya Rehat Singh Kohli", position: "AI Masters Co-Lead", branch: "CSE ( 2nd Year )", image: "Divya Rehat Kohli.JPG", description: "Assist in AIM SIG leadership and mentoring.", socials: { instagram: "https://www.instagram.com/divyarehatsingh.k/", linkedin: "https://www.linkedin.com/in/divya-rehat-singh-kohli-9a43a0169", twitter: "#", }, },
  { name: "Anushka Tripathi", position: "AI Masters Coordinator", branch: "CSE-DS ( 1st Year )", image: "Anushka Tripathi.jpg", description: "Support AIM SIG activities and workshops.", socials: { instagram: "https://www.instagram.com/_.anushka._06?igsh=eG1obWlwN2J0ejJi", linkedin: "https://www.linkedin.com/in/anushka-tripathi-4b3485333?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app", twitter: "#", }, },
  { name: "Kiratmeet Singh", position: "AI Masters Coordinator", branch: "CSE-DS ( 1st Year )", image: "Kiratmeet Singh.jpg", description: "Support AIM SIG activities and workshops.", socials: { instagram: "https://www.instagram.com/_kirat.13?igsh=NzVianNicW52N2F6", linkedin: "https://www.linkedin.com/in/kiratmeet-singh-1313-ks?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app", twitter: "#", }, },

  //Circuit Masters
  { name: "Vinay Dhaka", position: "Circuit Masters Lead", branch: "ECE ( 3rd Year )", image: "/ Vinay Dhaka.jpg", description: "Heads the Circuitmasters Special Interest Group (CSIG).", socials: { instagram: "", linkedin: "https://www.linkedin.com/in/vinay-dhaka-04239230a?trk=universal-search-cluster", twitter: "#", }, },
  { name: "Bhumika Bhardwaj", position: "Circuit Masters Co-Lead", branch: "ECE ( 2nd Year )", image: "Bhumika Bharadwaj.jpg", description: " Assist in leading CSIG activities and projects.", socials: { instagram: "https://www.instagram.com/bhumikabharadwajj?igsh=MWZkNHZtdDhqOGVwcg==", linkedin: "https://www.linkedin.com/in/bhumika-bharadwaj-99a90a292?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app", twitter: "#", }, },
  { name: "Nakul Chadda", position: "Circuit Masters Coordinator", branch: "ECE ( 1st Year )", image: "nakul.jpg", description: "Support in organizing CSIG workshops and events.", socials: { instagram: "https://www.instagram.com/nakul_chadda?igsh=MXNnOWVyYTh4NWh5aA==", linkedin: "", twitter: "#", }, },
  { name: "Prajjwal Gupta", position: "Circuit Masters Coordinator", branch: "ECE ( 3rd Year )", image: "Prajjwal Shekhar Gupta.JPG", description: "Support in organizing CSIG workshops and events.", socials: { instagram: "https://www.instagram.com/c.est_prajjwal?igsh=MTN5MHNwZmYxNnZjcQ==", linkedin: "https://www.linkedin.com/in/prajjwal-shekhar-gupta-01582726a?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app", twitter: "#", }, },
  
];
